version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    environment:
      POSTGRES_USER: 'username'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'database'

    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@postgres.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
